# Generated by Django 5.0 on 2024-01-10 06:38

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccount',
            managers=[
                ('objects', accounts.models.UserAccountManager()),
            ],
        ),
    ]
